version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cake_site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ntktw2002
  web:
    build: .
    command: bash -c "
      sleep 5 &&
      python cake_site/manage.py migrate &&
      python cake_site/manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
